name: Daily Update

on:
  schedule:
    - cron: '0 21 * * *'  # Run daily at 9 PM UTC (5 PM New York time)
    - cron: '43 13 * * *'  # 12:15 AM UTC = 7:30 AM (8:15 AM New York time)

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        node-version: 20
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        node-version: 20
        python-version: 3.8
        
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Update Data
      run: |
        python update_data.py
